name = "backend"
compatibility_date = "2024-07-13"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTZhNDQ4ZmYtODJhOC00YmE2LWExMzctZjlhNmUyZjM2N2QyIiwidGVuYW50X2lkIjoiNTRhZDk2MzRlYzE4YmE4NjEyMzcyYjI5MThkOGVhMTYzYjI1NTRmOGYyNzdlYTNhNmJjMzE3NzVlNTAyNTJiZCIsImludGVybmFsX3NlY3JldCI6ImIyOTVmMTY4LTJlNzQtNDdiYy05NjczLWJjODcwYTY4MmIzOSJ9.qfUYDBtiDGmFO7Uf8azWXaV1a8H7Oi57Dw-VGgbWnJI"
JWT_KEY = "JFJRJIFRJIRFIJRFFMKFJNFRNRFJNJRFNTHNGTHGNRJFJEDFNJENJED"

